package main

const Version = "v0.1.1"

const CiEnvVar = "CI"
const TerraformEnvVar = "TF_ENV"
const ModulesFolder = "aws-terraform-modules"
const ConfigFile = "config.tf"
const ConfigModuleName = "config"
const EnvironmentFile = "environment.tf"
const TerraformBackendConfig = "terraform-backend.conf"

const WarningHeader = `######################################
##   DO NOT EDIT THIS FILE          ##
##   Generated by tfconfig          ##
######################################

`

func main() {
	// everything managed inside cli.go, go away from here mate
	Init()
}
